#!/bin/sh

# Fail on error and unset variables
set -eu

# Run the generated wrapper directly so hook execution does not depend on shell activation.
# We are not using direnv exec here because mise and direnv can result in conflicting PATH settings:
# See: https://mise.jdx.dev/direnv.html
exec "kettle-commit-msg" "$@"
