codecov:
  bot: "autobolt"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%