version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "rubocop-lts"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
