name: MRI 2.4, 2.5 (Ancient) Svc Adapters

permissions:
  contents: read

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - "*-stable"
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs ${{ matrix.ruby }} ${{ matrix.appraisal_name }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 2.4
          - ruby: "2.4"
            appraisal_name: "couch-1.17-r2.4"
            exec_cmd: "rake spec:orm:couch_potato"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          - ruby: "2.4"
            appraisal_name: "mongoid-7.3-b4.12"
            exec_cmd: "rake spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.5
          - ruby: "2.5"
            appraisal_name: "couch-1.17-r2.5"
            exec_cmd: "rake spec:orm:couch_potato"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          - ruby: "2.5"
            appraisal_name: "mongoid-7.4-b4.15"
            exec_cmd: "rake spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

    steps:
      ### COUCHDB
      - name: Start CouchDB
        uses: iamssen/couchdb-github-action@master
        if: "endsWith(matrix.exec_cmd, 'couch_potato')"
        with:
          couchdb-version: "3.4.1"

      ### MONGODB
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        if: "endsWith(matrix.exec_cmd, 'mongoid')"
        with:
          mongodb-version: "8.0"

      ### SMOKE-TEST
      - name: Smoke CouchDB
        if: "endsWith(matrix.exec_cmd, 'couch_potato')"
        run: |
          curl -f http://127.0.0.1:5984/
          curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"name": "admin", "password": "password"}' http://127.0.0.1:5984/_session

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the main Gemfile at all.
      - name: Install Root Appraisal
        run: bundle
      - name: Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
        run: bundle exec appraisal ${{ matrix.appraisal_name }} bundle
      - name: Run ${{ matrix.exec_cmd }} on ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
        run: bundle exec appraisal ${{ matrix.appraisal_name }} bundle exec ${{ matrix.exec_cmd }}
