name: Test Coverage

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  K_SOUP_COV_MIN_BRANCH: 76
  K_SOUP_COV_MIN_LINE: 92
  K_SOUP_COV_MIN_HARD: true
  K_SOUP_COV_FORMATTERS: "xml,rcov,lcov,tty"
  K_SOUP_COV_DO: true
  K_SOUP_COV_MULTI_FORMATTERS: true
  K_SOUP_COV_COMMAND_NAME: "Test Coverage"

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  coverage:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Code Coverage on ${{ matrix.ruby }}@current
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Appraisal.root.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Coverage
          - ruby: "ruby"
            appraisal: "coverage"
            exec_cmd: "kettle-test"
            rubygems: latest
            bundler: latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: true

      - name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
        id: bundleAppraisalAttempt1
        run: bundle exec appraisal ${{ matrix.appraisal }} install
        # Continue to the next step on failure
        continue-on-error: true

      # Effectively an automatic retry of the previous step.
      - name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
        id: bundleAppraisalAttempt2
        # If bundleAppraisalAttempt1 failed, try again here; Otherwise skip.
        if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' }}
        run: bundle exec appraisal ${{ matrix.appraisal }} install

      - name: Tests for ${{ matrix.ruby }}@current via ${{ matrix.exec_cmd }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}

      - name: Verify coverage reports
        run: |
          test -s coverage/lcov.info
          test -s coverage/coverage.xml

      - name: Upload coverage to Coveralls
        if: ${{ !env.ACT }}
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
          format: lcov
        continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}

      - name: Upload coverage to QLTY
        if: ${{ !env.ACT }}
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          files: coverage/lcov.info
          format: lcov
          skip-errors: false
        continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}

      - name: Upload coverage to CodeCov
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          use_oidc: true
          disable_search: true
          fail_ci_if_error: false
          files: coverage/lcov.info,coverage/coverage.xml
          verbose: true

      - name: Code Coverage Summary Report
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: ./coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '${{ env.K_SOUP_COV_MIN_LINE }} ${{ env.K_SOUP_COV_MIN_BRANCH }}'
        continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        with:
          recreate: true
          path: code-coverage-results.md
        continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
