# Targets the evergreen latest release of ruby, truffleruby, and jruby
#   and tests against the HEAD of runtime dependencies
name: Runtime Deps @ HEAD

permissions:
  contents: read

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Specs ${{ matrix.ruby }}@${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Appraisal.root.gemfile
    strategy:
      fail-fast: true
      matrix:
        include:
          # Ruby 3.4
          - ruby: "ruby"
            appraisal: "dep-heads"
            exec_cmd: "kettle-test"
            rubygems: latest
            bundler: latest

          # truffleruby-24.1 (targets Ruby 3.3 compatibility)
          - ruby: "truffleruby"
            appraisal: "dep-heads"
            exec_cmd: "kettle-test"
            rubygems: default
            bundler: default

          # jruby-10.0 (targets Ruby 3.4 compatibility)
          - ruby: "jruby"
            appraisal: "dep-heads"
            exec_cmd: "kettle-test"
            rubygems: default
            bundler: default
            experimental: true

    steps:
      - name: Checkout
        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Ruby & RubyGems
        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true

      - name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
        id: bundleAppraisalAttempt1
        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
        run: bundle exec appraisal ${{ matrix.appraisal }} install
        # Continue to the next step on failure
        continue-on-error: true

      # Effectively an automatic retry of the previous step.
      - name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
        id: bundleAppraisalAttempt2
        # If bundleAppraisalAttempt1 failed, try again here; Otherwise skip.
        if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' && (!env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby'))) }}
        run: bundle exec appraisal ${{ matrix.appraisal }} install

      - name: Tests for ${{ matrix.ruby }} via ${{ matrix.exec_cmd }}
        if: ${{ !env.ACT || (! startsWith(matrix.ruby, 'jruby') && !startsWith(matrix.ruby, 'truffleruby')) }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
