name: MRI 3.0, 3.1 (EOL)

permissions:
  contents: read

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Specs ${{ matrix.ruby }} ${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 3.0
          - ruby: "3.0"
            appraisal: "ar-6-1-r3"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.5.23'
            bundler: '2.5.23'

          - ruby: "3.0"
            appraisal: "ar-7-0-r3"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.5.23'
            bundler: '2.5.23'

          - ruby: "3.0"
            appraisal: "ar-7-1-r3.1"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.5.23'
            bundler: '2.5.23'

          - ruby: "3.0"
            appraisal: "sequel-5.86-r3.1"
            exec_cmd: "rake spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: '3.5.23'
            bundler: '2.5.23'

          - ruby: "3.1"
            appraisal: "ar-7-0-r3"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.5.23'
            bundler: '2.5.23'

          - ruby: "3.1"
            appraisal: "ar-7-1-r3.1"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.6.9'
            bundler: '2.6.9'

          - ruby: "3.1"
            appraisal: "rom-r3.1"
            exec_cmd: "rake spec:orm:rom"
            gemfile: "Appraisal.root"
            rubygems: '3.6.9'
            bundler: '2.6.9'

          - ruby: "3.1"
            appraisal: "sequel-5.86-r3.1"
            exec_cmd: "rake spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: '3.5.23'
            bundler: '2.5.23'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the primary Gemfile at all.
      - name: Install Root Appraisal
        run: bundle
      - name: Appraisal for ${{ matrix.appraisal }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Tests for ${{ matrix.ruby }} via ${{ matrix.exec_cmd }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
