---
# Lock/Unlock Deps Pattern
#
# Two often conflicting goals resolved!
#
#  - unlocked_deps.yml
#    - All runtime & dev dependencies, but does not have a `gemfiles/*.gemfile.lock` committed
#    - Uses an Appraisal2 "unlocked_deps" gemfile, and the current MRI Ruby release
#    - Know when new dependency releases will break local dev with unlocked dependencies
#    - Broken workflow indicates that new releases of dependencies may not work
#
#  - locked_deps.yml
#    - All runtime & dev dependencies, and has a `Gemfile.lock` committed
#    - Uses the project's main Gemfile, and the current MRI Ruby release
#    - Matches what contributors and maintainers use locally for development
#    - Broken workflow indicates that a new contributor will have a bad time
#
name: Deps Locked

permissions:
  contents: read

env:
  # Running coverage, but not validating minimum coverage,
  #   because it would be redundant with the coverage workflow.
  # Also we can validate all output formats without breaking CodeCov,
  #   since we aren't submitting these reports anywhere.
  K_SOUP_COV_MIN_BRANCH: 69
  K_SOUP_COV_MIN_LINE: 81
  K_SOUP_COV_MIN_HARD: false
  K_SOUP_COV_FORMATTERS: "html,xml,rcov,lcov,json,tty"
  K_SOUP_COV_DO: true
  K_SOUP_COV_MULTI_FORMATTERS: true
  K_SOUP_COV_COMMAND_NAME: "Test Coverage"

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Default rake task w/ main Gemfile.lock ${{ matrix.name_extra || '' }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby <whichever version is current, e.g., 3.4 as of 2025-07-12>
          - ruby: "ruby"
            exec_cmd: "rake"
            rubygems: latest
            bundler: latest
            experimental: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true

      - name: Checks the kitchen sink via ${{ matrix.exec_cmd }}
        run: bundle exec ${{ matrix.exec_cmd }}
