name: Ruby 3.0

permissions:
  contents: read

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Specs ${{ matrix.ruby }}@${{ matrix.appraisal }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Appraisal.root.gemfile
    strategy:
      matrix:
        include:
          # Ruby 3.0
          - ruby: "ruby-3.0"
            appraisal: "ruby-3-0"
            exec_cmd: "kettle-test"
            rubygems: '3.5.23'
            bundler: '2.5.23'

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true

      - name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
        id: bundleAppraisalAttempt1
        if: ${{ !env.ACT }}
        run: bundle exec appraisal ${{ matrix.appraisal }} install
        continue-on-error: true

      - name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
        id: bundleAppraisalAttempt2
        if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' && !env.ACT }}
        run: bundle exec appraisal ${{ matrix.appraisal }} install

      - name: Tests for ${{ matrix.ruby }} via ${{ matrix.exec_cmd }}
        if: ${{ !env.ACT }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
