name: MRI 2.6 & 2.7 (Unsupported)

permissions:
  contents: read

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - "*-stable"
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs ${{ matrix.ruby }} ${{ matrix.appraisal_name }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 2.6
          - ruby: "2.6"
            appraisal_name: "ar-6-1-r2"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.4.22'
            bundler: '2.4.22'
          - ruby: "2.6"
            appraisal_name: "sequel-5.86-r2.6"
            exec_cmd: "rake spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: '3.4.22'
            bundler: '2.4.22'

          # Ruby 2.7
          - ruby: "2.7"
            appraisal_name: "ar-7-0-r2"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.4.22'
            bundler: '2.4.22'
          - ruby: "2.7"
            appraisal_name: "ar-7-1-r2"
            exec_cmd: "rake spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: '3.4.22'
            bundler: '2.4.22'
          - ruby: "2.7"
            appraisal_name: "sequel-5.86-r2.7"
            exec_cmd: "rake spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: '3.4.22'
            bundler: '2.4.22'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the main Gemfile at all.
      - name: Install Root Appraisal
        run: bundle
      - name: Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
        run: bundle exec appraisal ${{ matrix.appraisal_name }} bundle
      - name: Run ${{ matrix.exec_cmd }} on ${{ matrix.ruby }}@${{ matrix.appraisal_name }}
        run: bundle exec appraisal ${{ matrix.appraisal_name }} bundle exec ${{ matrix.exec_cmd }}
